### ISSUE TITLE
Breadcrumb: add full path minus current page

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/platform.coop#75]

**Comment by greatislander** [comment]
@cherylhjli Reconsidering this— it looks really crowded. Thoughts?

![Screen shot of full breadcrumb](https://user-images.githubusercontent.com/605361/57620013-f091b500-755d-11e9-9eed-d1b693ea75f0.png)

**Comment by cherylhjli** [comment]
Breadcrumb to go up one level
Looks like:

< Back to [page up one level]
ex.
< Back to How Platform Coops Can Benefit You

Icon used: left chevron, green
Typography: Noto sans regular, 14px, #16605D

**Comment by greatislander** [comment]
Fixed in #82.
